#define BOOT bootloader
#define BRIUP C_BRI_UP
#define BRIDN C_BRI_DN
#define SEL BT_SEL
#define RESET sys_reset
#define BLE OUT_BLE
#define USB OUT_USB
#define IDLE soft_off
#define TOG OUT_TOG
#define CSLEFT LC(LS(LEFT))
#define CSRIGHT LC(LS(RIGHT))